### ISSUE TITLE
libfile-slurp-perl required in Linux

### ISSUE THREAD

**Issue by alfem** [zgarnog/issuu-pub-dl#2]
I have tested it in an Ubuntu 16.04 derivative and it worked perfectly.

But I needed to install perl::slurp from libfile-slurp-perl package first.

**Comment by zgarnog** [comment]
That's great, thanks for testing it and commenting here! :)

I should add this to the documentation / README at some point as well

**Comment by zgarnog** [comment]
@alfem I have updated the README and released v1.4.0 with a few additional fixes

https://github.com/zgarnog/issuu-pub-dl/tree/v1.4.0#ubuntu-linux-derivative
