### ISSUE TITLE
Blocked by age-check

### ISSUE THREAD

**Issue by ganego** [zgarnog/issuu-pub-dl#3]
Hi, found your script but I have a problem, since issuu wants me to login to the page:

"Content Warning
This publication may contain content that is inappropriate for some users, as flagged by issuu's user community. "

Any plans to support this?
Thank you.

**Comment by zgarnog** [comment]
@ganego  I don't have plans to address that. Getting around that would probably require getting around their requirement for you to log in. And, you could create an account for free, right?

Sorry for the delayed reply. I don't check here often.

**Comment by ganego** [comment]
No problem :)
